[project]
name = "fw-ipsets"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "netaddr>=1.3.0",
    "pydantic>=2.12.4",
    "rich>=14.2.0",
    "toml>=0.10.2",
]
